### ISSUE TITLE
Relicense to CC BY NC SA rather than CC BY NC ND

### ISSUE THREAD

**Issue by mystise** [Futureazoo/TextureRepository#5]
https://creativecommons.org/licenses/by-nc-sa/4.0/

This will allow recolors and other changes to better fit the use case, and will require the changed textures to also be licensed under the same license. You'll have to clear this with https://github.com/Sunconure11 and any other contributors until you have a CLA.

**Comment by Futureazoo** [comment]
Thank you for catching this!

**Comment by Sunconure11** [comment]
I'm okay with this
